# Generated by Django 5.0.4 on 2024-04-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_cellphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='text',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='about',
            field=models.TextField(default='about'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experience',
            field=models.CharField(default='experience', max_length=255),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='major',
            field=models.CharField(default='major', max_length=255),
        ),
        migrations.AddField(
            model_name='time',
            name='hour',
            field=models.CharField(default='hour', max_length=255),
        ),
    ]
