# Generated by Django 5.0.4 on 2024-05-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_time_text_doctorprofile_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='major',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='hour',
            field=models.CharField(max_length=255),
        ),
    ]
