# Generated by Django 5.0.4 on 2024-05-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
