# Generated by Django 5.0.4 on 2024-05-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_time_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
